### ISSUE TITLE
Wake word not detected

### ISSUE THREAD

**Issue by TheStigh** [relust/VisualStreamAssist#5]
Hi,

When saying the wake word, nothing happen on the tablet.

I did follow your youtube guide and did following:

- Voice Assistant Pipeline set up within HA, called Piper (working) 
- Tablet (Samsung T585 with Android 8), Fully Kiosk Plus, set up as per video)
- RtcMic according per video (when I speak I can see it detects is within the RtcMic app)
- HACS-> Visual Stream Assistant -> Rebooted
- Integration -> Added Visual Stream Assistant
-- Settings within the Visual Voice Assistant integration:
```
rtp://192.168:11.135:5555 <IP of my tablet>
media_player.ha_display
ha_display
tts.piper
language=en-us&voice=en_US-ryan-high
How can I help you?, Yes listening, Whats up?
local/gifs/jarvis_speech.gif
local/gifs/jarvis_listen.gif
```

What am I doing wrong?

**Comment by relust** [comment]
you tablet ip rtp://192.168:11.135:5555 is write wrong, try rtp://192.168.11.135:5555

**Comment by TheStigh** [comment]
> you tablet ip rtp://192.168:11.135:5555 is write wrong, try rtp://192.168.11.135:5555

Thanks, but that was actually written correctly in my config.

![image](https://github.com/user-attachments/assets/77314a49-7f7c-4678-866b-1b174a4f1059)

**Comment by relust** [comment]
![visual stream assist ](https://github.com/user-attachments/assets/0bdb9a2f-b3d0-4f4b-a8f0-5f55549b2058)
At my ip, here it is written with "." not with ":"

**Comment by TheStigh** [comment]
You are so absolutely right!
Now I can see it hear me, but I do not receive the welcome message, nor is there any browser_mod popup....

**Comment by relust** [comment]
Try using edge tts instead of pipper tts, check that the "Browser mod Browser Id" name is spelled exactly the same as the one on the tablet from Browser mod tab, and make sure you copy the gifs to the "www/gifs/” directory, and write the answers (how can I help you, yes listening, whats up) without any other punctuation between them, only with a comma

**Comment by TheStigh** [comment]
It just suddenly started to work, didn't need to anything more... Thanx @relust !
